# Needs inliner
# npm install -g inliner

all :
	inliner waiting/index.html > wait.html
	inliner home/index.html > home.html

wait :
	inliner waiting/index.html > wait.html

home :
	inliner home/index.html > home.html
